// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package public

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/tokoonline/app/internal/httpx"
	"github.com/tokoonline/app/internal/models"
	"github.com/tokoonline/app/internal/views/layouts"
)

type CheckoutData struct {
	Cart     *models.Cart
	Subtotal float64
	Weight   int
	Email    string
	Name     string
	Phone    string
	Channel  string // b2c | b2b
	IsTOP    bool
	TOPDays  int
}

func Checkout(d layouts.PageData, cd CheckoutData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1 class=\"h1\">Checkout</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(cd.Cart.Items) == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>Keranjang kosong. <a href=\"/c/semua\">Belanja dulu</a>.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form hx-post=\"/checkout\" hx-swap=\"none\" hx-disable-during-request=\"true\"><input type=\"hidden\" name=\"csrf_token\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(d.CSRFToken)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 28, Col: 62}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><div class=\"grid\" style=\"grid-template-columns:1fr 360px;gap:1.5rem\"><div><div class=\"card\"><h3 class=\"h3\">Kontak</h3><div class=\"form-grid\"><div class=\"field\"><label>Email</label> <input class=\"input\" type=\"email\" name=\"email\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(cd.Email)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 36, Col: 72}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" required></div><div class=\"field\"><label>Nama Lengkap</label> <input class=\"input\" name=\"name\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(cd.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 40, Col: 57}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" required></div></div><div class=\"field\"><label>Nomor HP</label> <input class=\"input\" name=\"phone\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(cd.Phone)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 45, Col: 58}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" required></div></div><div class=\"card\" style=\"margin-top:1rem\"><h3 class=\"h3\">Alamat Pengiriman</h3><div class=\"field\"><label>Cari Kecamatan/Kota</label> <input class=\"input\" id=\"area-q\" placeholder=\"Ketik nama kecamatan, kota...\" hx-get=\"/api/shipping/areas\" hx-trigger=\"keyup changed delay:400ms\" hx-target=\"#area-results\" hx-include=\"this\" name=\"q\"><div id=\"area-results\" style=\"background:#fff;border:1px solid var(--c-line);border-radius:.5rem;margin-top:.25rem;max-height:240px;overflow:auto\"></div><input type=\"hidden\" name=\"ship_area_id\" id=\"ship_area_id\" required> <input type=\"hidden\" name=\"ship_province\" id=\"ship_province\"> <input type=\"hidden\" name=\"ship_city\" id=\"ship_city\"> <input type=\"hidden\" name=\"ship_district\" id=\"ship_district\"></div><div class=\"field\"><label>Kode Pos</label> <input class=\"input\" name=\"ship_postal_code\" id=\"ship_postal_code\" required></div><div class=\"field\"><label>Alamat lengkap</label> <textarea class=\"input\" name=\"ship_address\" rows=\"3\" required></textarea></div></div><div class=\"card\" style=\"margin-top:1rem\"><h3 class=\"h3\">Kurir</h3><button class=\"btn btn-outline btn-sm\" type=\"button\" hx-get=\"/api/shipping/rates\" hx-include=\"[name='ship_area_id'],[name='ship_postal_code']\" hx-target=\"#rates\" hx-vals=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(`js:{weight:` + intToString(cd.Weight) + `}`)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 70, Col: 223}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\">Cek Ongkir</button><div id=\"rates\" style=\"margin-top:.5rem\"></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if cd.Channel == "b2b" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"card\" style=\"margin-top:1rem\"><h3 class=\"h3\">Metode Pembayaran</h3><label style=\"display:block;margin-bottom:.5rem\"><input type=\"radio\" name=\"payment_term\" value=\"prepaid\" checked> Bayar Sekarang (Xendit)</label> ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if cd.IsTOP {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<label style=\"display:block\"><input type=\"radio\" name=\"payment_term\" value=\"top\"> Bayar Tempo (TOP ")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						var templ_7745c5c3_Var8 string
						templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(intToString(cd.TOPDays))
						if templ_7745c5c3_Err != nil {
							return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 78, Col: 134}
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " hari) — generate PO</label>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<input type=\"hidden\" name=\"payment_term\" value=\"prepaid\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"card\" style=\"margin-top:1rem\"><h3 class=\"h3\">Catatan (opsional)</h3><textarea class=\"input\" name=\"notes\" rows=\"2\"></textarea></div></div><aside class=\"summary\"><h3 class=\"h3\">Ringkasan</h3>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, it := range cd.Cart.Items {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"sum-row\" style=\"font-size:.85rem\"><span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(it.ProductName)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 93, Col: 30}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " × ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(intToString(it.Qty))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 93, Col: 57}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</span> <span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 string
					templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(httpx.IDR(it.UnitPrice * float64(it.Qty)))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 94, Col: 57}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</span></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<div class=\"sum-row\"><span>Subtotal</span><span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(httpx.IDR(cd.Subtotal))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 97, Col: 78}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</span></div><div class=\"sum-row\"><span>Ongkos Kirim</span><span id=\"shipping-cell\">-</span></div><input type=\"hidden\" name=\"shipping_total\" id=\"shipping_total\" value=\"0\"> <input type=\"hidden\" name=\"courier_code\" id=\"courier_code\"> <input type=\"hidden\" name=\"courier_service\" id=\"courier_service\"><div class=\"sum-row sum-grand\"><span>Total</span><span id=\"grand-cell\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var13 string
				templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(httpx.IDR(cd.Subtotal))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/public/checkout.templ`, Line: 102, Col: 101}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</span></div><button class=\"btn btn-accent btn-block\" type=\"submit\" style=\"margin-top:1rem\">Bayar Sekarang</button><p class=\"muted\" style=\"font-size:.75rem;margin-top:.75rem\">Dengan menekan tombol di atas, Anda menyetujui <a href=\"/p/syarat-ketentuan\">Syarat & Ketentuan</a>.</p></aside></div></form><script>\n\t\t\t(function(){\n\t\t\t\tconst subtotal = { JSStr(cd.Subtotal) };\n\t\t\t\tdocument.body.addEventListener('click',(e)=>{\n\t\t\t\t\tif(e.target.matches('[data-area]')){\n\t\t\t\t\t\tconst a = e.target.dataset;\n\t\t\t\t\t\tdocument.getElementById('ship_area_id').value=a.area;\n\t\t\t\t\t\tdocument.getElementById('ship_province').value=a.province;\n\t\t\t\t\t\tdocument.getElementById('ship_city').value=a.city;\n\t\t\t\t\t\tdocument.getElementById('ship_district').value=a.district;\n\t\t\t\t\t\tif(a.postal){document.getElementById('ship_postal_code').value=a.postal}\n\t\t\t\t\t\tdocument.getElementById('area-q').value=a.label;\n\t\t\t\t\t\tdocument.getElementById('area-results').innerHTML='';\n\t\t\t\t\t}\n\t\t\t\t\tif(e.target.matches('[data-rate]')){\n\t\t\t\t\t\tconst a=e.target.dataset;\n\t\t\t\t\t\tdocument.getElementById('shipping_total').value=a.price;\n\t\t\t\t\t\tdocument.getElementById('courier_code').value=a.code;\n\t\t\t\t\t\tdocument.getElementById('courier_service').value=a.service;\n\t\t\t\t\t\tdocument.getElementById('shipping-cell').textContent='Rp '+Number(a.price).toLocaleString('id-ID');\n\t\t\t\t\t\tdocument.getElementById('grand-cell').textContent='Rp '+Number(subtotal+parseFloat(a.price)).toLocaleString('id-ID');\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t\tdocument.body.addEventListener('htmx:afterRequest',(e)=>{\n\t\t\t\t\tif(e.detail.elt.matches('form')&&e.detail.successful){\n\t\t\t\t\t\ttry{ const r=JSON.parse(e.detail.xhr.responseText); if(r.redirect){location.href=r.redirect;} }catch{}\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t})();\n\t\t\t</script>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Public(d).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func JSStr(v float64) string {
	intPart := int(v)
	return intToString(intPart)
}

var _ = templruntime.GeneratedTemplate
